import Foundation
import AppKit

// MARK: - Settings

enum ClipboardSettings {
    static let persistKey = "clipboard.persistHistory"
    static let capacityKey = "clipboard.capacity"
    static let excludedAppsKey = "clipboard.excludedApps"
    static let hotkeyKey = "clipboard.quickPasteHotkey"

    static let capacities = [20, 50, 100, 200, 500]
    /// Secrets are kept in memory only, and only this long.
    static let secretLifetime: TimeInterval = 120

    /// Password managers and credential apps that mark (or should mark) their
    /// copies as private. Users can add / remove apps in Settings → Clipboard.
    static let defaultExcludedApps = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal",
        "in.sinew.Enpass-Desktop",
        "org.keepassxc.keepassxc",
    ]

    static func register() {
        UserDefaults.standard.register(defaults: [
            persistKey: true,
            capacityKey: 100,
            excludedAppsKey: defaultExcludedApps,
            hotkeyKey: QuickPasteHotkey.controlCommandV.rawValue,
        ])
    }

    static var persist: Bool { UserDefaults.standard.bool(forKey: persistKey) }
    static var capacity: Int { max(10, UserDefaults.standard.integer(forKey: capacityKey)) }
    static var excludedApps: [String] {
        UserDefaults.standard.stringArray(forKey: excludedAppsKey) ?? defaultExcludedApps
    }
}

// MARK: - Privacy

enum ClipboardPrivacy {
    /// nspasteboard.org markers that password managers and other apps set on
    /// copies a clipboard manager must not record.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    static func isMarkedPrivate(_ pasteboard: NSPasteboard) -> Bool {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        return !types.isDisjoint(with: privateTypes)
    }

    private static let secretPatterns: [NSRegularExpression] = [
        #"^eyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]*$"#,   // JWT
        #"\bsk-(?:proj-|ant-)?[A-Za-z0-9_-]{20,}"#,                          // OpenAI / Anthropic keys
        #"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}"#,                      // GitHub tokens
        #"\bgithub_pat_[A-Za-z0-9_]{40,}"#,
        #"\bglpat-[A-Za-z0-9_-]{20,}"#,                                      // GitLab
        #"\bAKIA[0-9A-Z]{16}\b"#,                                            // AWS access key
        #"\bAIza[0-9A-Za-z_-]{35}\b"#,                                       // Google API key
        #"\bxox[abprs]-[A-Za-z0-9-]{10,}"#,                                  // Slack
        #"\b(?:sk|rk)_live_[A-Za-z0-9]{20,}"#,                               // Stripe
        #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#,                              // PEM keys
    ].compactMap { try? NSRegularExpression(pattern: $0) }

    /// Tokens and keys we recognise by shape. Matching items are masked,
    /// never written to disk, and dropped after `secretLifetime`.
    static func looksLikeSecret(_ text: String) -> Bool {
        let s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard s.count >= 20, s.count < 20_000 else { return false }
        let range = NSRange(s.startIndex..., in: s)
        return secretPatterns.contains { $0.firstMatch(in: s, range: range) != nil }
    }

    static func masked(_ text: String) -> String {
        let s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard s.count > 10 else { return String(repeating: "•", count: s.count) }
        return String(s.prefix(6)) + String(repeating: "•", count: 10) + String(s.suffix(4))
    }
}

// MARK: - Persistence

/// History lives in ~/Library/Application Support/Swordfish/Clipboard as
/// `history.json` plus one PNG per image item. Files are created 0600.
enum ClipboardStore {
    static let directory: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        return base.appendingPathComponent("Swordfish/Clipboard", isDirectory: true)
    }()
    static let imagesDirectory = directory.appendingPathComponent("images", isDirectory: true)
    private static let historyFile = directory.appendingPathComponent("history.json")

    static func ensureDirectories() {
        try? FileManager.default.createDirectory(at: imagesDirectory, withIntermediateDirectories: true,
                                                 attributes: [.posixPermissions: 0o700])
    }

    static func loadHistory() -> [ClipboardItem] {
        guard let data = try? Data(contentsOf: historyFile) else { return [] }
        return (try? JSONDecoder().decode([ClipboardItem].self, from: data)) ?? []
    }

    static func saveHistory(_ items: [ClipboardItem]) {
        write(items.filter { $0.kind != .secret }, to: historyFile)
    }

    static func deleteHistoryFile() {
        try? FileManager.default.removeItem(at: historyFile)
    }

    /// Removes image files no longer referenced by any item.
    static func pruneImages(keeping names: Set<String>) {
        let files = (try? FileManager.default.contentsOfDirectory(atPath: imagesDirectory.path)) ?? []
        for file in files where !names.contains(file) {
            try? FileManager.default.removeItem(at: imagesDirectory.appendingPathComponent(file))
        }
    }

    private static func write<T: Encodable>(_ value: T, to url: URL) {
        ensureDirectories()
        guard let data = try? JSONEncoder().encode(value) else { return }
        try? data.write(to: url, options: .atomic)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}

// MARK: - Smart actions

/// What a clipboard text *is*, beyond text/link/code — drives the one-click
/// actions on each history row.
enum ClipboardContentType: Equatable {
    case json, jwt, timestamp(Date), base64(String), url(URL), hexColor(NSColor), uuid, plain
}

enum ClipboardSmartActions {
    static func detect(_ text: String) -> ClipboardContentType {
        let s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !s.isEmpty, s.count < 1_000_000 else { return .plain }

        if (s.hasPrefix("{") || s.hasPrefix("[")),
           (try? JSONSerialization.jsonObject(with: Data(s.utf8))) != nil {
            return .json
        }
        if s.hasPrefix("eyJ"), (try? DevUtilities.decodeJWT(s)) != nil { return .jwt }
        if UUID(uuidString: s) != nil { return .uuid }
        if s.allSatisfy(\.isNumber), [10, 13].contains(s.count),
           let result = DevUtilities.parseTimestamp(s),
           // 2001…2100 — avoids treating phone numbers / IDs as dates.
           (978_307_200...4_102_444_800).contains(result.date.timeIntervalSince1970) {
            return .timestamp(result.date)
        }
        if let color = hexColor(s) { return .hexColor(color) }
        if !s.contains(where: \.isWhitespace), let url = URL(string: s), let scheme = url.scheme,
           scheme.count >= 2, (url.host != nil || !["http", "https"].contains(scheme)), s.contains(":") {
            return .url(url)
        }
        if let decoded = base64Text(s) { return .base64(decoded) }
        return .plain
    }

    /// `#RGB`, `#RRGGBB`, `#RRGGBBAA` (with or without `#`, but then exactly 6 hex digits).
    private static func hexColor(_ s: String) -> NSColor? {
        var hex = s
        if hex.hasPrefix("#") { hex.removeFirst() } else if hex.count != 6 { return nil }
        guard [3, 6, 8].contains(hex.count), hex.allSatisfy(\.isHexDigit) else { return nil }
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
        guard let value = UInt64(hex, radix: 16) else { return nil }
        let hasAlpha = hex.count == 8
        let r = Double((value >> (hasAlpha ? 24 : 16)) & 0xFF) / 255
        let g = Double((value >> (hasAlpha ? 16 : 8)) & 0xFF) / 255
        let b = Double((value >> (hasAlpha ? 8 : 0)) & 0xFF) / 255
        let a = hasAlpha ? Double(value & 0xFF) / 255 : 1
        return NSColor(srgbRed: r, green: g, blue: b, alpha: a)
    }

    /// Only strings that are clearly base64 (length, alphabet, padding) and
    /// decode to readable UTF-8 — plain words would otherwise match.
    private static func base64Text(_ s: String) -> String? {
        guard s.count >= 12, s.count % 4 == 0,
              s.range(of: #"^[A-Za-z0-9+/]+={0,2}$"#, options: .regularExpression) != nil,
              s.contains(where: \.isNumber) || s.hasSuffix("=") || s.contains("+") || s.contains("/"),
              let data = Data(base64Encoded: s),
              let text = String(data: data, encoding: .utf8),
              !text.isEmpty,
              text.unicodeScalars.allSatisfy({ !CharacterSet.controlCharacters.contains($0) || $0 == "\n" || $0 == "\t" })
        else { return nil }
        return text
    }

    static func swiftUIColor(_ c: NSColor) -> String {
        let c = c.usingColorSpace(.sRGB) ?? c
        return String(format: "Color(red: %.3f, green: %.3f, blue: %.3f)", c.redComponent, c.greenComponent, c.blueComponent)
    }

    static func uiColor(_ c: NSColor) -> String {
        let c = c.usingColorSpace(.sRGB) ?? c
        return String(format: "UIColor(red: %.3f, green: %.3f, blue: %.3f, alpha: %.2f)",
                      c.redComponent, c.greenComponent, c.blueComponent, c.alphaComponent)
    }
}

// MARK: - Transforms

enum ClipboardTransform: CaseIterable, Identifiable {
    case trim, uppercase, lowercase, camelCase, snakeCase, sortLines, uniqueLines, jsonEscape, jsonUnescape

    var id: Self { self }
    var label: String {
        switch self {
        case .trim:         return String(localized: "Trim whitespace")
        case .uppercase:    return String(localized: "UPPERCASE")
        case .lowercase:    return String(localized: "lowercase")
        case .camelCase:    return String(localized: "camelCase")
        case .snakeCase:    return String(localized: "snake_case")
        case .sortLines:    return String(localized: "Sort lines")
        case .uniqueLines:  return String(localized: "Remove duplicate lines")
        case .jsonEscape:   return String(localized: "Escape as JSON string")
        case .jsonUnescape: return String(localized: "Unescape JSON string")
        }
    }

    func apply(_ s: String) -> String? {
        switch self {
        case .trim:
            return s.split(separator: "\n", omittingEmptySubsequences: false)
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .joined(separator: "\n")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        case .uppercase: return s.uppercased()
        case .lowercase: return s.lowercased()
        case .camelCase:
            let words = Self.words(s)
            guard let first = words.first else { return s }
            return first.lowercased() + words.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }.joined()
        case .snakeCase:
            return Self.words(s).map { $0.lowercased() }.joined(separator: "_")
        case .sortLines:
            return s.split(separator: "\n", omittingEmptySubsequences: false)
                .map(String.init)
                .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
                .joined(separator: "\n")
        case .uniqueLines:
            var seen = Set<String>()
            return s.split(separator: "\n", omittingEmptySubsequences: false)
                .map(String.init)
                .filter { seen.insert($0).inserted }
                .joined(separator: "\n")
        case .jsonEscape:
            guard let data = try? JSONSerialization.data(withJSONObject: s, options: [.fragmentsAllowed, .withoutEscapingSlashes]) else { return nil }
            return String(decoding: data, as: UTF8.self)
        case .jsonUnescape:
            let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
            let quoted = t.hasPrefix("\"") ? t : "\"\(t)\""
            return (try? JSONSerialization.jsonObject(with: Data(quoted.utf8), options: .fragmentsAllowed)) as? String
        }
    }

    /// Splits "fooBar baz-qux_quux" into ["foo", "Bar", "baz", "qux", "quux"].
    private static func words(_ s: String) -> [String] {
        var words: [String] = []
        var current = ""
        var previous: Character?
        for ch in s {
            if !ch.isLetter && !ch.isNumber {
                if !current.isEmpty { words.append(current); current = "" }
            } else if ch.isUppercase, let p = previous, p.isLowercase || p.isNumber {
                if !current.isEmpty { words.append(current) }
                current = String(ch)
            } else {
                current.append(ch)
            }
            previous = ch
        }
        if !current.isEmpty { words.append(current) }
        return words
    }
}
